$Color1 = rgb(bd93f9)
$Color2 = rgb(50fa7b)
$Color3 = rgb(ff5555)
$Color4=  rgb(f1fa8c)
# $Color1 = rgb(180, 190, 254)
# $Color2 = rgb(148, 226, 213)
# $Color3 = rgb(243, 139, 168)


general {
    ignore_empty_input = true
    immediate_render = true
}

background {
    # color = rgba(0,0,0,0.33)
    # crossfade_time = 100
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = easeOutQuint,0.25,1,0.25,1.05
    animation = fadeIn, 0, 0, linear
    animation = fadeOut, 0, 0, linear

    animation = inputFieldColors,1 ,1, linear
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.5 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1
    outer_color = $Color4
    inner_color = rgba(30, 31, 41, 1)
    font_color = $Color4
    fade_on_empty = false
    rounding = 0
    check_color = $Color    
    placeholder_text = <i>Input Password...</i>
    fail_text = <i>sus ඞ</i>
    fail_color = $Color3
    check_color = $Color2
    font_family = JetBrainsMono Nerd Font
    hide_input = false
    position = -42, -230
    halign = center
    valign = center
    # shadow_passes = 1
    # shadow_size = 5
}


# Whoami
label {
    monitor =
    # text = cmd[update:1000] echo "$(whoami)"
    text = Jan Äärelä
    color = $Color2
    font_size = 22
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -150
    halign = center
    valign = center
    # shadow_size = 10
    # shadow_passes = 3


}


# Language 
label {
    text = cmd[update:100] hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap' | cut -c1-2 | tr 'A-Z' 'a-z'
    font_family = JetBrainsMono Nerd Font
    font_size = 20
    position = 160,-230
    color = $Color4
}



# THE BOX
shape {
    size = 450,635
    border_size = 3
    border_color = $Color1
    color = rgba(40, 42, 54, 0.66)
    position = 0, 25
    rounding = 0
    shadow_passes = 1
    shadow_passes = 3
    shadow_size = 5
}

# Language box
shape {
    size = 64,64
    border_size = 3
    border_color = $Color4
    color = rgba(30, 31, 41, 1)
    position = 160, -230
    rounding = 0
    shadow_passes = 1
    # shadow_passes = 3
    # shadow_size = 5
    onclick = hyprctl switchxkblayout current next

}


# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = $Color2
    font_size = 22
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 300
    halign = center
    valign = center
    # shadow_passes = 3
    # shadow_size = 5
}

# TIME
label {
    monitor = 
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $Color2
    font_size = 95
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 200
    halign = center
    valign = center
    # shadow_passes = 3
    # shadow_size = 5
}

# Profile Picture
image {
    monitor =
    # path = /home/jan-aarela/Pictures/zani-1x1-m.png
    path = /home/jan-aarela/Pictures/memz/zani-sp-mocha.png
    size = 200
    border_size = 4
    rounding = 0
    border_color = $Color2
    position = 0, 0
    halign = center
    valign = center
    # shadow_passes = 3
    # shadow_size = 5
    onclick = paplay ~/.config/sounds/kanni_paalle.mp3
}

